name: Dev Workflow - Test and check things

on:
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Install deps
        run: go mod tidy

      - name: Install gomobile
        run: go get golang.org/x/mobile/cmd/gomobile

      - name: Install charset
        run: go get golang.org/x/net/html/charset

      - name: Install ipv4
        run: go get golang.org/x/net/ipv4

      - name: Install ipv6
        run: go get golang.org/x/net/ipv6

      - name: Install golangci
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0

      - name: Lint
        run: golangci-lint run

      - name: Test
        run: go test -p 1 -v ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella