name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Install gomobile
        run: go get golang.org/x/mobile/cmd/gomobile

      - name: Test
        run: go test -v ./...

      - name: Build
        run: cd mobile && gomobile init && go generate