name: Go

on:
  push:
    branches: [ master, alpha.0 ]
  pull_request:
    branches: [ master, alpha.0 ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Install deps
        run: go mod tidy

      - name: Install gomobile
        run: go get golang.org/x/mobile/cmd/gomobile

      - name: Install charset
        run: go get golang.org/x/net/html/charset

      - name: Install ipv4
        run: go get golang.org/x/net/ipv4

      - name: Install ipv6
        run: go get golang.org/x/net/ipv6

      - name: Test
        run: go test -timeout 120s -p 1 -v ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella

      - name: Build
        run: cd mobile && gomobile init && go generate